spring.application.name=RevShop_BackEnd


spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


# Root logging level
logging.level.root=INFO

# Your package logging (more detailed)
logging.level.com.revshop_backend=DEBUG

# Console format
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n

# File logging
logging.file.name=revshop-backend.log
logging.file.path=logs  

jwt.secret=revshopSecretKey
jwt.expiration=86400000

